name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    name: Release - ${{ matrix.platform.target }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            arch: x64
          - os: windows-latest
            target: i686-pc-windows-msvc
            arch: x86
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            arch: arm64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bins: cargo-deb, cargo-generate-rpm
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            bins: cross, cargo-deb, cargo-generate-rpm
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            bins: cross, cargo-deb, cargo-generate-rpm
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            bins: cross, cargo-deb, cargo-generate-rpm
          - os: ubuntu-latest
            target: x86_64-unknown-freebsd
            bins: cross
          - os: ubuntu-latest
            target: i686-unknown-freebsd
            bins: cross
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: moonrepo/setup-rust@v1
        with:
          targets: ${{ matrix.platform.target }}
          bins: ${{ matrix.platform.bins }}
          cache: false

      - name: Build binary
        shell: pwsh
        run: |
          $tool = if ("${{ matrix.platform.bins }}".Contains("cross")) { "cross" } else { "cargo" }
          & $tool build --target ${{ matrix.platform.target }} --release --locked

      - name: Create Deb package
        if: contains(matrix.platform.bins, 'cargo-deb')
        shell: pwsh
        run: |
          $nightly = if ($env:GITHUB_EVENT_NAME -eq 'workflow_run') { "--deb-version=nightly" } else { "" }
          cargo deb --target ${{ matrix.platform.target }} --no-build --no-strip $nightly

      - name: Create RPM package
        if: contains(matrix.platform.bins, 'cargo-generate-rpm')
        shell: pwsh
        run: |
          $nightly = if ($env:GITHUB_EVENT_NAME -eq 'workflow_run') { "--set-metadata=version=`"nightly`"" } else { "" }
          cargo generate-rpm --target ${{ matrix.platform.target }} $nightly

      - name: Rename binary
        id: rename_binary
        shell: pwsh
        run: |
          $bin = if ($env:RUNNER_OS -eq 'Windows') { "komac.exe" } else { "komac" }
          $newName = "komac"
          if ($env:GITHUB_EVENT_NAME -eq 'workflow_run') {
            $newName += "-nightly"
          } else {
            $newName += "-$($env:GITHUB_REF_NAME.TrimStart('v'))"
          }
          $newName += "-${{ matrix.platform.target }}"
          if ($env:RUNNER_OS -eq 'Windows') {
            $newName += ".exe"
            Rename-Item -Path "target/${{ matrix.platform.target }}/release/$bin" -NewName "$newName"
          }
          "name=$newName" >> $env:GITHUB_OUTPUT

      - name: Create Tar archive
        if: ${{ runner.os != 'Windows' }}
        run: |
          tar -czvf ${{ steps.rename_binary.outputs.name }}.tar.gz -C target/${{ matrix.platform.target }}/release komac
          rm target/${{ matrix.platform.target }}/release/komac

      - name: Create Inno Installer
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |
          $input = "../target/${{ matrix.platform.target }}/release/${{ steps.rename_binary.outputs.name }}"
          iscc.exe assets/installer.iss `
            /DInputExecutable=$input `
            /DArchitecture=${{ matrix.platform.arch }} `
            /F$("${{ steps.rename_binary.outputs.name }}".Replace("komac", "komac-setup").TrimEnd(".exe"))

      - name: Compute SHA256 checksum
        shell: pwsh
        run: |
          Get-Item -ErrorAction SilentlyContinue -Path "${{ steps.rename_binary.outputs.name }}.tar.gz","assets/Output/*","target/${{ matrix.platform.target }}/release/*","target/${{ matrix.platform.target }}/debian/*","target/${{ matrix.platform.target }}/generate-rpm/*" -Include "komac-*", "komac*.deb", "komac*.rpm" | ForEach-Object {
            $FileHash = (Get-FileHash -Path $_.FullName -Algorithm SHA256).Hash.ToLower()
            New-Item -Force -ItemType File -Path $_.DirectoryName -Name "$($_.Name).sha256" -Value "$FileHash *$($_.Name)`n"
          }

      - name: Set Release variables
        id: set_release_vars
        shell: pwsh
        run: |
          if ($env:GITHUB_EVENT_NAME -eq 'workflow_run') {
            "name=Nightly release" >> $env:GITHUB_OUTPUT
            "tag_name=nightly" >> $env:GITHUB_OUTPUT
            "prerelease=true" >> $env:GITHUB_OUTPUT
            "generate_release_notes=false" >> $env:GITHUB_OUTPUT
          } else {
            "prerelease=false" >> $env:GITHUB_OUTPUT
            "generate_release_notes=true" >> $env:GITHUB_OUTPUT
          }

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            target/${{ matrix.platform.target }}/release/${{ steps.rename_binary.outputs.name }}
            target/${{ matrix.platform.target }}/release/${{ steps.rename_binary.outputs.name }}.sha256
            target/${{ matrix.platform.target }}/debian/*.deb
            target/${{ matrix.platform.target }}/debian/*.sha256
            target/${{ matrix.platform.target }}/generate-rpm/*.rpm
            target/${{ matrix.platform.target }}/generate-rpm/*.sha256
            ${{ steps.rename_binary.outputs.name }}.tar.gz
            ${{ steps.rename_binary.outputs.name }}.tar.gz.sha256
            assets/Output/*


